var tree = [["[Global Namespace]",,"",
                [["CreateTbMessboardBansTable","CreateTbMessboardBansTable.html"," < Migration",
                [        ]],["CreateTbMessboardCommentsTable","CreateTbMessboardCommentsTable.html"," < Migration",
                [        ]],["CreateTbMessboardLikesTable","CreateTbMessboardLikesTable.html"," < Migration",
                [        ]],["CreateTbMessboardPermissionRoleTable","CreateTbMessboardPermissionRoleTable.html"," < Migration",
                [        ]],["CreateTbMessboardPermissionsTable","CreateTbMessboardPermissionsTable.html"," < Migration",
                [        ]],["CreateTbMessboardPostsTable","CreateTbMessboardPostsTable.html"," < Migration",
                [        ]],["CreateTbMessboardRolesTable","CreateTbMessboardRolesTable.html"," < Migration",
                [        ]],["CreateTbMessboardUserRoleTable","CreateTbMessboardUserRoleTable.html"," < Migration",
                [        ]],["CreateTbMessboardViewsTable","CreateTbMessboardViewsTable.html"," < Migration",
                [        ]],["MessageBoardSeeder","MessageBoardSeeder.html"," < Seeder",
                [        ]]        ]],["MicheleAngioni",,"",
                [["MessageBoard","MicheleAngioni\/MessageBoard.html","",
                [["Models","MicheleAngioni\/MessageBoard\/Models.html","",
                [["Ban","MicheleAngioni\/MessageBoard\/Models\/Ban.html"," < Model",
                [        ]],["Comment","MicheleAngioni\/MessageBoard\/Models\/Comment.html"," < Model",
                [        ]],["Like","MicheleAngioni\/MessageBoard\/Models\/Like.html"," < Model",
                [        ]],["Permission","MicheleAngioni\/MessageBoard\/Models\/Permission.html"," < Model",
                [        ]],["Post","MicheleAngioni\/MessageBoard\/Models\/Post.html"," < Model",
                [        ]],["Role","MicheleAngioni\/MessageBoard\/Models\/Role.html"," < Model",
                [        ]],["View","MicheleAngioni\/MessageBoard\/Models\/View.html"," < Model",
                [        ]]        ]],["Presenters","MicheleAngioni\/MessageBoard\/Presenters.html","",
                [["CommentPresenter","MicheleAngioni\/MessageBoard\/Presenters\/CommentPresenter.html"," < AbstractPresenter",
                [        ]],["PostPresenter","MicheleAngioni\/MessageBoard\/Presenters\/PostPresenter.html"," < AbstractPresenter",
                [        ]]        ]],["Repos","MicheleAngioni\/MessageBoard\/Repos.html","",
                [["CommentRepositoryInterface","MicheleAngioni\/MessageBoard\/Repos\/CommentRepositoryInterface.html","",
                [        ]],["EloquentCommentRepository","MicheleAngioni\/MessageBoard\/Repos\/EloquentCommentRepository.html"," < AbstractEloquentRepository",
                [        ]],["EloquentLikeRepository","MicheleAngioni\/MessageBoard\/Repos\/EloquentLikeRepository.html"," < AbstractEloquentRepository",
                [        ]],["EloquentPermissionRepository","MicheleAngioni\/MessageBoard\/Repos\/EloquentPermissionRepository.html"," < AbstractEloquentRepository",
                [        ]],["EloquentPostRepository","MicheleAngioni\/MessageBoard\/Repos\/EloquentPostRepository.html"," < AbstractEloquentRepository",
                [        ]],["EloquentRoleRepository","MicheleAngioni\/MessageBoard\/Repos\/EloquentRoleRepository.html"," < AbstractEloquentRepository",
                [        ]],["EloquentViewRepository","MicheleAngioni\/MessageBoard\/Repos\/EloquentViewRepository.html"," < AbstractEloquentRepository",
                [        ]],["LikeRepositoryInterface","MicheleAngioni\/MessageBoard\/Repos\/LikeRepositoryInterface.html","",
                [        ]],["PermissionRepositoryInterface","MicheleAngioni\/MessageBoard\/Repos\/PermissionRepositoryInterface.html","",
                [        ]],["PostRepositoryInterface","MicheleAngioni\/MessageBoard\/Repos\/PostRepositoryInterface.html","",
                [        ]],["RoleRepositoryInterface","MicheleAngioni\/MessageBoard\/Repos\/RoleRepositoryInterface.html","",
                [        ]],["ViewRepositoryInterface","MicheleAngioni\/MessageBoard\/Repos\/ViewRepositoryInterface.html","",
                [        ]]        ]],["AbstractMbGateway","MicheleAngioni\/MessageBoard\/AbstractMbGateway.html","",
                [        ]],["MbGateway","MicheleAngioni\/MessageBoard\/MbGateway.html"," < AbstractMbGateway",
                [        ]],["MbGatewayInterface","MicheleAngioni\/MessageBoard\/MbGatewayInterface.html","",
                [        ]],["MbTrait","MicheleAngioni\/MessageBoard\/MbTrait.html","",
                [        ]],["MbUserInterface","MicheleAngioni\/MessageBoard\/MbUserInterface.html","",
                [        ]],["MessageBoardServiceProvider","MicheleAngioni\/MessageBoard\/MessageBoardServiceProvider.html"," < ServiceProvider",
                [        ]],["PermissionManager","MicheleAngioni\/MessageBoard\/PermissionManager.html","",
                [        ]],["Purifier","MicheleAngioni\/MessageBoard\/Purifier.html","",
                [        ]],["PurifierInterface","MicheleAngioni\/MessageBoard\/PurifierInterface.html","",
                [        ]]        ]]        ]]        ]

